# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "github-issue-reporter"
description: "Generates reports (typically daily) of potentially stale issues or issues that need attention."
inputs:
  repository:
    description: "The GitHub issue repository to generate the report for."
    required: false
    default: $GITHUB_REPOSITORY
  prs:
    description: "The GitHub code repository to generate the report for, if different to issue repository."
    required: false
    default: ''    
  githubToken:
    description: "The Github token or PAT token (preferred) for API access."
    required: true
  reportPath:
    description: "Path of report folder"
    required: false
    default: "reports"
  reportNameTemplate:
    description: "File name template for reports. Can use metacharacters understood by Python strftime."
    required: false
    default: "report-%a.md"
  team:
    description: "Comma-separated list of team members. Start with + if this is comprehensive."
    required: false
    default: ''
  days:
    description: "Time window (in days) for reports. Used to determine what items are new since last report."
    required: false
    default: '1'
  all:
    description: "Whether to show all items or only those that are new (based on time window)."
    required: false
    default: false
  hotspots:
    description: "Whether to show a report on frequently changed files."
    required: false
    default: false    
  branch:
    description: "The branch to use for pushing the reports to."
    required: false
    default: 'main'
runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        ref: ${{ inputs.branch }}
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install numpy 1.x # Despite pinning numpy in ghreport next step installs numpy 2 so trying this 
      run:
        python -m pip install numpy==1.26.4
      shell: bash          
    - name: Install reporter
      run:
        python -m pip install ghreport
      shell: bash
    - name: Ensure directory exists
      run:
        mkdir -p ${{ inputs.reportPath }}
      shell: bash
    - name: Generate full report with hotspots
      if: ${{ inputs.all == 'true' && inputs.hotspots == 'true' }} 
      run:
        ghreport report -h -T -a -o ${{ inputs.reportPath }}/${{ inputs.reportNameTemplate }} -p ${{ inputs.prs }} -t ${{ inputs.team }} -d ${{ inputs.days }} ${{ inputs.repository }} ${{ inputs.githubToken }}
      shell: bash    
    - name: Generate full report
      if: ${{ inputs.all == 'true' && inputs.hotspots != 'true' }}
      run:
        ghreport report -T -a -o ${{ inputs.reportPath }}/${{ inputs.reportNameTemplate }} -p ${{ inputs.prs }} -t ${{ inputs.team }} -d ${{ inputs.days }} ${{ inputs.repository }} ${{ inputs.githubToken }}
      shell: bash
    - name: Generate limited report
      if: ${{ inputs.all != 'true' }}
      run:
        ghreport report -T -o ${{ inputs.reportPath }}/${{ inputs.reportNameTemplate }} -p ${{ inputs.prs }} -t ${{ inputs.team }} -d ${{ inputs.days }} ${{ inputs.repository }} ${{ inputs.githubToken }}
      shell: bash
    - name: Commit report
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git pull
        git add -A
        git status
        git commit -m "Daily report update" -a
      shell: bash
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.githubToken }}
        branch: ${{ inputs.branch }}
